"""Context store interface. Two implementations satisfy it: in-memory dicts (memory.py, the dev
default — fast, no deps, lost on restart) and Postgres (db.py — durable). Routes depend only on
this interface, so the backend is selected by config (STORE_BACKEND) with no route changes."""
from __future__ import annotations

from typing import Protocol

from ..schemas import (
    ChunkAnalysis,
    ClassUnit,
    GrowthPath,
    PathMemory,
    QAEntry,
    RunResult,
    Score,
    Segment,
    TargetedQuestion,
)


class Store(Protocol):
    # lifecycle (no-ops for the memory store)
    async def init(self) -> None: ...
    async def dispose(self) -> None: ...

    # transcript
    async def get_transcript(self, session_id: str) -> list[Segment]: ...
    async def append_segment(self, session_id: str, segment: Segment) -> None: ...

    # confusion analyses (per-chunk)
    async def get_analyses(self, session_id: str) -> list[ChunkAnalysis]: ...
    async def append_analysis(self, session_id: str, analysis: ChunkAnalysis) -> None: ...
    async def set_analyses(self, session_id: str, analyses: list[ChunkAnalysis]) -> None: ...

    # measurement run + raw scores
    async def set_run(self, session_id: str, result: RunResult, scores: list[Score]) -> None: ...
    async def get_run(self, session_id: str) -> RunResult | None: ...
    async def get_scores(self, session_id: str) -> list[Score]: ...

    # targeted-question ledger
    async def get_history(self, session_id: str) -> list[QAEntry]: ...
    async def next_question_id(self, session_id: str) -> int: ...
    async def record_questions(self, session_id: str, questions: list[TargetedQuestion]) -> None: ...
    async def record_answer(self, session_id: str, question_id: int, answer: str) -> bool: ...
    async def covered_chunk_ids(self, session_id: str) -> set[int]: ...

    # session topic
    async def set_topic(self, session_id: str, topic: str) -> None: ...
    async def get_topic(self, session_id: str) -> str: ...

    # learning plan (growth path) — keyed by path_id
    async def save_path(self, path: GrowthPath) -> None: ...
    async def get_path(self, path_id: str) -> GrowthPath | None: ...
    async def save_class(self, path_id: str, cls: ClassUnit) -> None: ...

    # cross-class memory — keyed by path_id
    async def get_memory(self, path_id: str) -> PathMemory: ...
    async def update_memory(self, path_id: str, memory: PathMemory) -> None: ...
